newrelic:
  license: '' # New Relic license key
  version: '3' # bump this everytime you upload a changed worker

# Iron.io credentials (where you launch your agent)
iron:
  project_id: ''
  token: ''

# Desk.com configuration
desk:
  support_email: ''
  subdomain: ''
  key: ''
  secret: ''
  oauth_token: ''
  oauth_secret: ''

